#!/usr/bin/env python3
"""Build the Forecast Channel weather patch for one revision of City Folk.

  build_patch.py --accf <sys/main.dol of the revision> --donor <Mario & Sonic main.dol> --out <dir>
                 [--ref <RUUE02 main.dol, default: same as --accf>] [--rev RUUE02]

The patch is written against City Folk Deluxe (USA); wregions.py finds every address in the other revisions.

Steps: generate the relocatable FCD assembly from the donor, compile the glue,
link everything at BASE, verify that every transplanted branch still reaches the
instruction it reached in the donor, then write the patch description.
"""
import argparse, os, re, struct, subprocess, sys, json

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import fcdgen
import wregions
from dol import Dol

GCC_DIR = os.environ.get("DEVKITPPC", "/opt/devkitpro/devkitPPC") + "/bin/"
GCC, LD, OBJCOPY, NM = (GCC_DIR + "powerpc-eabi-" + t for t in ("gcc", "ld", "objcopy", "nm"))
CFLAGS = ["-mcpu=750", "-O2", "-ffreestanding", "-fno-builtin", "-fno-common", "-msdata=none", "-I", HERE]

LINK_OBJS = ["hooks.o", "weather.o", "fcd_fetch.o", "fcd_loader.o", "fcd_relocated.o"]

# disc id / version byte of every revision (what Riivolution matches on), and a label
REVS = {
    "RUUE01v0": ("RUUE01", 0, "Animal Crossing: City Folk (USA, Rev 0)"),
    "RUUE01v1": ("RUUE01", 1, "Animal Crossing: City Folk (USA/Asia, Rev 1)"),
    "RUUP01v0": ("RUUP01", 0, "Animal Crossing: Let's Go to the City (Europe, Rev 0)"),
    "RUUP01v1": ("RUUP01", 1, "Animal Crossing: Let's Go to the City (Europe, Rev 1)"),
    "RUUJ01v1": ("RUUJ01", 1, "Machi e Ikou yo: Doubutsu no Mori (Japan, Rev 1)"),
    "RUUJ01v2": ("RUUJ01", 2, "Machi e Ikou yo: Doubutsu no Mori (Japan, Rev 2)"),
    "RUUK01v1": ("RUUK01", 1, "Tauneuro Nolleogayo: Dongmurui Sup (Korea, Rev 1)"),
    "RUUE02": ("RUUE02", 0, "Animal Crossing: City Folk Deluxe (USA)"),
    "RUUP02": ("RUUP02", 0, "Animal Crossing: City Folk Deluxe (PAL)"),
    "RUUJ02": ("RUUJ02", 1, "Animal Crossing: City Folk Deluxe (Japan)"),
    "RUUK02": ("RUUK02", 0, "Animal Crossing: City Folk Deluxe (Korea)"),
}


def run(cmd):
    subprocess.check_call(cmd)


def write_region(out, r, link_word):
    """region.h (C), region.ld (linker) for one revision's addresses"""
    h = lambda v: "0x%08Xu" % v
    open(os.path.join(out, "region.h"), "w").write("\n".join([
        "/* generated by build_patch.py */",
        "#define accf_lock          ((s32 (*)(void))%s)" % h(r["lock"]),
        "#define accf_unlock        ((s32 (*)(void))%s)" % h(r["unlock"]),
        "#define accf_cal_to_ticks  ((u64 (*)(const CalTime *))%s)" % h(r["cal_to_ticks"]),
        "#define accf_get_time      ((u64 (*)(void))%s)" % h(r["get_time"]),
        "#define accf_bus_clock()   (*(volatile u32 *)0x800000F8)",
        "#define vf_is_init         ((s32 (*)(void))%s)" % h(r["vf_is_init"]),
        "#define vf_init            ((void (*)(void *, u32))%s)" % h(r["vf_init"]),
        "#define vf_shutdown        ((void (*)(void))%s)" % h(r["vf_shutdown"]),
        "#define VF_BUF_SIZE        0x4000",
        "#define vf_open  ((void *(*)(const char *, const char *))%s)" % h(r["vf_open"]),
        "#define vf_read  ((s32 (*)(void *, void *, u32, u32 *))%s)" % h(r["vf_read"]),
        "#define vf_close ((s32 (*)(void *))%s)" % h(r["vf_close"]),
        "#define ACCF_CITY_TABLE    %s" % h(r["city_table"]),
        "#define ACCF_CALENDAR      %s" % h(r["calendar"]),
        "#define SDA_SCENE_KIND     (%d)" % r["scene_kind"],
        "#define SDA_NWC_HEAP       (%d)" % r["nwc_heap_ptr"],
        ""]))
    ld = ["/* generated by build_patch.py */"]
    for name, site in (("type_now", "type_now"), ("type_next", "type_next"), ("tv", "tv"), ("link", "link"), ("pad", "pad")):
        ld.append("ret_%s = 0x%08x;" % (name, r[site] + 4))
    for name in ("OSSetMEM1ArenaLo", "OSRegisterVersion", "VFMount", "VFUnmount", "NANDOpen", "NANDGetLength", "NANDRead", "NANDClose"):
        ld.append("accf_%s = 0x%08x;" % (name, r[name]))
    for off, a in zip(wregions.RT_OFFS, r["rt"]):
        ld.append("accf_rt_%08x = 0x%08x;" % (0x8044E808 + off, a))
    open(os.path.join(out, "region.ld"), "w").write("\n".join(ld) + "\n")


def build_blob(donor, out, region, link_word, trace=False, selftest=False):
    base = region["base"]
    os.makedirs(out, exist_ok=True)
    write_region(out, region, link_word)
    src, info = fcdgen.generate(donor, trace=trace)
    asm = os.path.join(out, "fcd_relocated.S")
    open(asm, "w").write(src)
    obj = lambda n: os.path.join(out, n)
    for c in ("weather", "fcd_fetch", "fcd_loader"):
        run([GCC] + CFLAGS + ["-I", out] + (["-DWEATHER_SELFTEST"] if selftest and c == "weather" else []) + ["-c", os.path.join(HERE, c + ".c"), "-o", obj(c + ".o")])
    run([GCC, "-mcpu=750", "-Wa,-mregnames", "-DACCF_DISP_LINK=0x%08X" % link_word, "-c", os.path.join(HERE, "hooks.S"), "-o", obj("hooks.o")])
    run([GCC, "-mcpu=750", "-Wa,-mregnames", "-c", asm, "-o", obj("fcd_relocated.o")])
    elf = obj("weather.elf")
    run([LD, "-L", out, "-T", os.path.join(HERE, "link.ld"), "--defsym", "BASE=0x%08X" % base, "-e", "0", "-o", elf] + [obj(o) for o in LINK_OBJS])
    binf = obj("weather.bin")
    run([OBJCOPY, "-O", "binary", elf, binf])
    syms = {}
    for line in subprocess.check_output([NM, elf]).decode().splitlines():
        p = line.split()
        if len(p) == 3:
            syms[p[2]] = int(p[0], 16)
    return open(binf, "rb").read(), syms, info


def verify_transplant(blob, base, syms, info):
    """Every branch in the relocated FCD code must reach the same target as in the donor."""
    D = info["donor"]
    start = syms["FCDGetWorkMemorySize"]
    # relocated code spans from FCDGetWorkMemorySize to the end of the FCD text (next data symbol)
    end = syms["fcd_text_end"]
    words = struct.unpack(">%dI" % ((end - start) // 4), blob[start - base:end - base])
    label = {int(k[2:], 16): v for k, v in syms.items() if re.fullmatch(r"L_[0-9a-f]{8}", k)}
    ext = {addr: syms[name] for addr, name in fcdgen.EXT.items()}
    dw = D.words(fcdgen.START, (fcdgen.END - fcdgen.START) // 4)
    sizes = info["sizes"]
    j, bad, checked = 0, [], 0
    for i, x in enumerate(dw):
        a = fcdgen.START + 4 * i
        if a not in sizes:
            continue                                  # FCD_LoadLZ, replaced
        op = x >> 26
        new_a = label.get(a)
        if new_a is not None and new_a != start + 4 * j:
            bad.append("label %#x expected at %#x got %#x" % (a, start + 4 * j, new_a))
        y = words[j]
        if op in (16, 18):
            t = fcdgen.branch_target(a, x)
            want = label[t] if t in label else ext[t]
            got = fcdgen.branch_target(start + 4 * j, y)
            checked += 1
            if got != want or (y & 1) != (x & 1) or (y >> 26) != op:
                bad.append("branch at donor %#x: target %#x want %#x" % (a, got, want))
        elif sizes[a] == 1 and y != x and (y >> 26) != (x >> 26):
            bad.append("unexpected change at donor %#x: %08x -> %08x" % (a, x, y))
        j += sizes[a]
    if j * 4 != end - start:
        bad.append("walked %d words, relocated code has %d" % (j, (end - start) // 4))
    return checked, bad


def verify_data_refs(blob, base, syms, info):
    """Every rewritten data reference must compute exactly the address of its intended object."""
    start, end = syms["FCDGetWorkMemorySize"], syms["fcd_text_end"]
    words = struct.unpack(">%dI" % ((end - start) // 4), blob[start - base:end - base])
    s16 = fcdgen.s16
    idx, j = {}, 0
    for a in sorted(info["sizes"]):
        idx[a] = j
        j += info["sizes"][a]

    def addr_of_use(k, sign_extend=True):
        """relocated word k is `op rD,imm(rA)` / addi / ori; find the feeding lis and return the address"""
        x = words[k]
        op, rt, ra = x >> 26, (x >> 21) & 31, (x >> 16) & 31
        reg = rt if op == 24 else ra
        for b in range(k - 1, max(k - 400, -1), -1):
            y = words[b]
            if (y >> 26) == 15 and ((y >> 21) & 31) == reg and ((y >> 16) & 31) == 0:
                hi = (y & 0xFFFF) << 16
                return (hi | (x & 0xFFFF)) if op == 24 else (hi + s16(x & 0xFFFF)) & 0xFFFFFFFF
        return None

    bad, n_obj, n_sda = [], 0, 0
    for a, (obj, off) in sorted(info["use_fix"].items()):
        got = addr_of_use(idx[a])
        want = syms[obj] + off
        n_obj += 1
        if got != want:
            bad.append("use at donor %#x: %s+%d want %#x got %s" % (a, obj, off, want, hex(got) if got else None))
    for a, sym in sorted(info["sda_uses"].items()):
        k = idx[a] + 1                                   # second instruction of the pair
        got = addr_of_use(k)
        n_sda += 1
        if got != syms[sym]:
            bad.append("SDA access at donor %#x: %s want %#x got %s" % (a, sym, syms[sym], hex(got) if got else None))
    for name, size in (("fcd_ctx", 0x20), ("fcd_vff_paths", 12), ("fcd_save_paths", 12)):
        lo = syms[name] & 0xFFFF
        if (lo & 0x8000) != ((lo + size - 1) & 0x8000):
            bad.append("%s straddles a @ha carry boundary" % name)
    return n_obj, n_sda, bad


# ---- patch sites in main.dol: (region key, expected original word, trampoline, is_bl)
SITES = [
    ("type_now",  0x9421FFF0, "tramp_type_now",  False),   # stwu r1,-0x10(r1)   dWeather type, this hour
    ("type_next", 0x9421FFF0, "tramp_type_next", False),   # stwu r1,-0x10(r1)   dWeather type, next hour
    ("tv",        0x9421FFF0, "tramp_tv",        False),   # stwu r1,-0x10(r1)   TV forecast program
    ("link",      None,       "tramp_link",      False),   # lwz  r4,SDA(r13)    module link request (displacement varies)
    ("pad",       0x907F0854, "tramp_pad",       False),   # stw  r3,0x854(r31)  after KPADRead
    ("arena_call", None,      "tramp_arena",     True),    # bl   OSSetMEM1ArenaLo (OSInit)
]
# NWC24 heap size: 0x5C800 -> 0xA4800, room for the 0x48000-byte forecast buffer
STATIC = [("nwc_heap", bytes.fromhex("3C600006" "3863C800"), bytes.fromhex("3C60000A" "38634800"))]
FIRST_FREE_TEXT_SLOT = 2


def enc_branch(site, target, link):
    off = target - site
    assert -0x2000000 <= off < 0x2000000 and off % 4 == 0
    return struct.pack(">I", 0x48000000 | (off & 0x03FFFFFC) | (1 if link else 0))


def dol_reader(raw):
    hdr_off = struct.unpack(">18I", raw[0:72]); hdr_addr = struct.unpack(">18I", raw[72:144]); hdr_size = struct.unpack(">18I", raw[144:216])
    def read(va, n):
        for i in range(18):
            if hdr_size[i] and hdr_addr[i] <= va < hdr_addr[i] + hdr_size[i]:
                return raw[hdr_off[i] + va - hdr_addr[i]: hdr_off[i] + va - hdr_addr[i] + n]
        raise SystemExit("address %#x not in the DOL" % va)
    return read


def collect_patches(raw, region, blob, syms):
    """[(address, bytes)] for main.dol memory, after verifying every site holds what we expect."""
    read = dol_reader(raw)
    base = region["base"]
    patches = []
    for key, orig, tramp, link in SITES:
        site = region[key]
        w = struct.unpack(">I", read(site, 4))[0]
        if link:
            orig = struct.unpack(">I", enc_branch(site, region["OSSetMEM1ArenaLo"], True))[0]
        if orig is not None and w != orig:
            raise SystemExit("site %#x (%s) holds %08x, expected %08x: wrong revision?" % (site, key, w, orig))
        patches.append((site, enc_branch(site, syms[tramp], link)))
    for key, old, new in STATIC:
        addr = region[key]
        if read(addr, len(old)) != old:
            raise SystemExit("static patch site %#x does not hold the expected bytes" % addr)
        patches.append((addr, new))
    size = (syms["weather_blob_end"] - base)
    patches.append((base, blob.ljust(size, b"\0")))
    return patches


def apply_patches(raw, patches, base):
    """patched copy of a main.dol image (bytes): the writes, plus the blob as a new text section"""
    raw = bytearray(raw)
    off = list(struct.unpack(">18I", raw[0:72])); addr = list(struct.unpack(">18I", raw[72:144])); size = list(struct.unpack(">18I", raw[144:216]))
    blob_patch = [p for p in patches if p[0] == base][0]
    def to_file(va):
        for i in range(18):
            if size[i] and addr[i] <= va < addr[i] + size[i]:
                return off[i] + va - addr[i]
        return None
    for va, data in patches:
        if va == base:
            continue
        fo = to_file(va)
        assert fo is not None
        raw[fo:fo + len(data)] = data
    for a, s in zip(addr, size):
        if s and a < base + len(blob_patch[1]) and base < a + s:
            raise SystemExit("0x%08X overlaps an existing section" % base)
    slot = next((i for i in range(FIRST_FREE_TEXT_SLOT, 7) if size[i] == 0), None)
    if slot is None:
        raise SystemExit("no free text section in the DOL header")
    while len(raw) % 32:
        raw.append(0)
    off[slot], addr[slot], size[slot] = len(raw), base, len(blob_patch[1])
    raw += blob_patch[1]
    raw[0:72] = struct.pack(">18I", *off); raw[72:144] = struct.pack(">18I", *addr); raw[144:216] = struct.pack(">18I", *size)
    return bytes(raw)


def riivolution_xml(rev, patches):
    disc_id, version, label = REVS[rev]
    L = ['<!-- %s -- External (Forecast Channel) weather -->' % label,
         '<wiidisc version="1" root="/">',
         '  <id game="%s" version="%d" />' % (disc_id, version),
         '  <options>',
         '    <section name="Animal Crossing: City Folk">',
         '      <option name="External Weather (Forecast Channel)" default="1">',
         '        <choice name="Enabled"><patch id="weather" /></choice>',
         '      </option>',
         '    </section>',
         '  </options>',
         '  <patch id="weather">']
    for va, data in patches:
        for k in range(0, len(data), 0x400):
            chunk = data[k:k + 0x400]
            L.append('    <memory offset="0x%08X" value="%s" />' % (va + k, chunk.hex().upper()))
    L += ['  </patch>', '</wiidisc>']
    return "\n".join(L) + "\n"


def build_rev(rev, accf, ref, donor, out, trace=False, selftest=False):
    """Build the patch for one revision; writes main.weather.dol, <rev>-weather.xml, weather-patch.json into out."""
    raw = open(accf, "rb").read()
    region = wregions.resolve(Dol(ref), Dol(accf))
    link_word = struct.unpack(">I", dol_reader(raw)(region["link"], 4))[0]
    base = region["base"]
    blob, syms, info = build_blob(donor, out, region, link_word, trace=trace, selftest=selftest)
    checked, bad = verify_transplant(blob, base, syms, info)
    print("%s: blob %#x bytes at %#010x (ends %#010x)" % (rev, len(blob), base, base + len(blob)))
    print("  transplant check: %d branches verified, %d problems" % (checked, len(bad)))
    nobj, nsda, bad2 = verify_data_refs(blob, base, syms, info)
    print("  data references: %d object refs, %d SDA replacement refs, %d problems" % (nobj, nsda, len(bad2)))
    for b in (bad + bad2)[:10]:
        print("   ", b)
    if bad or bad2:
        raise SystemExit("%s: verification failed" % rev)
    patches = collect_patches(raw, region, blob, syms)
    open(os.path.join(out, "main.weather.dol"), "wb").write(apply_patches(raw, patches, base))
    open(os.path.join(out, "%s-weather.xml" % rev), "w").write(riivolution_xml(rev, patches))
    info_json = {"rev": rev, "disc_id": REVS[rev][0], "region": {k: v for k, v in region.items() if k != "rt"}, "base": base, "blob_end": syms["weather_blob_end"],
                 "patches": [{"address": va, "bytes": d.hex(), "old": dol_reader(raw)(va, len(d)).hex()} for va, d in patches if va != base],
                 "blob": blob.ljust(syms["weather_blob_end"] - base, b"\0").hex(),
                 "symbols": {k: v for k, v in syms.items() if k.startswith(("tramp_", "FCD", "fcd_", "weather_", "g_", "out."))},
                 "trace_names": info.get("trace_names", [])}
    json.dump(info_json, open(os.path.join(out, "weather-patch.json"), "w"), indent=1)
    print("  patches: %d memory writes + blob" % (len(patches) - 1))
    return info_json


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--accf", required=True, help="main.dol of the revision to patch")
    ap.add_argument("--donor", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--ref", help="RUUE02 main.dol the addresses are written against (default: --accf itself)")
    ap.add_argument("--rev", default="RUUE02", help="revision key (see REVS)")
    ap.add_argument("--selftest", action="store_true", help="test build: fetch once at the title (never ship)")
    ap.add_argument("--trace", action="store_true", help="record FCDInit call results in fcd_trace (diagnostics)")
    a = ap.parse_args()
    build_rev(a.rev, a.accf, a.ref or a.accf, a.donor, a.out, trace=a.trace, selftest=a.selftest)
    return 0


if __name__ == "__main__":
    sys.exit(main())
