#!/usr/bin/env python3
"""Generate weather_map.inc (Forecast Channel condition code -> City Folk weather type).

Input: WiiLink24/ForecastChannel weather.xml (the <conditions> block).
  https://raw.githubusercontent.com/WiiLink24/ForecastChannel/main/weather.xml

City Folk weather types: 0 clear, 1 mild overcast, 2 heavy overcast,
3 rain, 4 heavy rain, 5 snow, 6 heavy snow.

Each <condition> has an international `code_2` and a Japanese `japanese_code_2`
that both point at the same condition, so one decision table keyed on the
condition `code` covers both. The Japanese codes are coarse (several conditions
share one), so the shared ones are resolved explicitly in JP2_OVERRIDE.
"""
import sys, urllib.request, xml.etree.ElementTree as ET

URL = "https://raw.githubusercontent.com/WiiLink24/ForecastChannel/main/weather.xml"

# condition <code> -> City Folk type
TYPE = {
    1: 0, 2: 0, 3: 0,                   # Sunny, Mostly Sunny, Partly Cloudy
    4: 1, 5: 1, 6: 1,                   # Intermittent Clouds, Haze, Mostly Cloudy
    7: 2, 8: 2, 11: 2,                  # Cloudy, Overcast, Fog
    12: 3, 13: 3, 14: 3, 18: 3,         # Showers variants, Rain
    15: 4, 16: 4, 17: 4,                # Thunderstorms variants
    19: 5, 20: 5, 21: 5, 23: 5, 24: 5, 25: 5, 26: 5, 29: 5,   # flurries, snow-ish, ice, sleet, freezing rain, rain and snow
    22: 6,                              # Snow
    30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 0,                 # Hot, Cold, Windy, Clear, Mostly Clear, Partly Cloudy (night)
    36: 1, 37: 1, 38: 1,                # Intermittent Clouds, Hazy Moonlight, Mostly Cloudy (night)
    39: 3, 40: 3, 41: 4, 42: 4, 43: 5, 44: 5,                 # night variants
}

# japanese_code_2 values shared by conditions of different type -> chosen type
JP2_OVERRIDE = {
    0x0001: 0,   # Sunny/Mostly Sunny/Haze/Hot/Cold/Windy
    0x0002: 1,   # Partly Cloudy / Intermittent Clouds
    0x000A: 2,   # Mostly Cloudy/Cloudy/Overcast/Fog
    0x000C: 5,   # Mostly Cloudy with Showers/Flurries/Snow (fixed to snow)
    0x800A: 1,   # night Partly Cloudy/Intermittent/Hazy Moonlight/Mostly Cloudy
    0x801A: 5,   # Flurries/Snow/Ice/Sleet/Freezing Rain (heavy snow unreachable)
}

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else None
    data = open(src, "rb").read() if src else urllib.request.urlopen(URL).read()
    root = ET.fromstring(data)
    table = {}
    def put(code, t, what):
        if code in table and table[code] != t:
            raise SystemExit(f"conflict for code {code:#06x}: {table[code]} vs {t} ({what})")
        table[code] = t
    seen_jp = {}
    for c in root.iter("condition"):
        g = lambda tag: (c.findtext(tag) or "").strip()
        k = int(g("code")); t = TYPE[k]
        put(int(g("code_2"), 16), t, f"code_2 of {k}")
        seen_jp.setdefault(int(g("japanese_code_2"), 16), set()).add(t)
    for code, types in seen_jp.items():
        if code in JP2_OVERRIDE:
            put(code, JP2_OVERRIDE[code], "japanese_code_2 override")
        elif len(types) == 1:
            put(code, next(iter(types)), "japanese_code_2")
        else:
            raise SystemExit(f"japanese_code_2 {code:#06x} is ambiguous {types}; add it to JP2_OVERRIDE")
    lines = ["/* generated by gen_weather_map.py - do not edit */",
             "/* Forecast Channel condition code -> City Folk weather type (sorted by code) */"]
    lines += [f"    {{ 0x{code:04X}, {t} }}," for code, t in sorted(table.items())]
    open("weather_map.inc", "w").write("\n".join(lines) + "\n")
    print(f"{len(table)} codes written to weather_map.inc")

if __name__ == "__main__":
    main()
